force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <label>End_Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Location__c.field-meta.xml
<CustomField>
    <fullName>End_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Bookings (End Location)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/No_Of_Hours__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Hours__c</fullName>
    <formula>ROUND(( End_Datetime__c - Start_Datetime__c) * 24, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Of Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Start_Datetime__c</fullName>
    <label>Start Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Location__c.field-meta.xml
<CustomField>
    <fullName>Start_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Start Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Start Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>No_Of_Hours__c  * Vehicle__r.Rent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BookingController.cls
public with sharing class BookingController {
    
    @AuraEnabled
    public static List<Booking__c> getBookings(){
        return [SELECT Id, 
                Name, 
                Vehicle__c,
                Vehicle__r.Name,
                Vehicle__r.Rent__c, 
                Customer__r.Name, 
                Start_Datetime__c, 
                End_Datetime__c,
                End_Location__r.Name,
                Start_Location__r.Name,
                Status__c,
                No_Of_Hours__c,
                Total_Amount__c
                FROM  Booking__c 
                WITH SECURITY_ENFORCED
                ORDER BY Name
                LIMIT 50000];
        
    }
    
    @AuraEnabled
    public static Boolean isValidBooking(Id vehicleId, Datetime startDatetime, Datetime endDatetime){
        List<Booking__c> bookings = [SELECT Id, Name, Vehicle__c, Start_Datetime__c, End_Datetime__c
                                     FROM Booking__c 
                                     WHERE Vehicle__c =: vehicleId
                                     AND (
                                         Start_DateTime__c <= :endDatetime AND End_DateTime__c >= :startDatetime
                                     )
                                     WITH SECURITY_ENFORCED];
        
        return bookings.isEmpty();
    }

    @AuraEnabled(cacheable=true)
    public static List<Booking__c> getLocationById(Id recordId){
        return [SELECT Id, 
                Name, 
                Vehicle__r.Name,
                Vehicle__r.Rent__c, 
                Customer__r.Name, 
                Start_Datetime__c, 
                End_Datetime__c,
                End_Location__r.Name,
                Start_Location__r.Name,
                End_Location__r.Geolocation__Latitude__s,
                Start_Location__r.Geolocation__Latitude__s,
                End_Location__r.Geolocation__Longitude__s,
                Start_Location__r.Geolocation__Longitude__s
                FROM  Booking__c 
                WHERE Id =: recordId
                WITH SECURITY_ENFORCED
                ORDER BY Name
                LIMIT 50000];
        
    }
}